FROM debezium/connect:2.7.3.Final

USER root

# Create directory for Avro converter
RUN mkdir -p /kafka/connect/kafka-connect-avro-converter

WORKDIR /kafka/connect/kafka-connect-avro-converter

# Download ALL required dependencies for Avro converter
RUN curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/7.5.0/kafka-connect-avro-converter-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-data/7.5.0/kafka-connect-avro-data-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/7.5.0/kafka-avro-serializer-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.5.0/kafka-schema-serializer-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.5.0/kafka-schema-registry-client-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-schema-converter/7.5.0/kafka-schema-converter-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/common-config/7.5.0/common-config-7.5.0.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/common-utils/7.5.0/common-utils-7.5.0.jar && \
    curl -sLO https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.3/avro-1.11.3.jar && \
    curl -sLO https://repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar && \
    curl -sLO https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar && \
    curl -sLO https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar && \
    curl -sLO https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar

USER kafka