package main

var HtmlParts = []string{
	`<!DOCTYPE html>`,
	`<html lang="en">`,
	`<head>`,
	`<meta charset="UTF-8">`,
	`<meta name="viewport" content="width=device-width, initial-scale=1.0">`,
	`<title>My Awesome Page</title>`,
	`<link rel="stylesheet" href="/static/css/main.css">`,
	`<link rel="stylesheet" href="/static/css/components.css">`,
	`</head>`,
	`<body>`,
	`<header class="site-header">`,
	`<nav class="navbar">`,
	`<a href="/" class="logo">MyBrand</a>`,
	`<ul class="nav-links">`,
	`<li><a href="/about">About</a></li>`,
	`<li><a href="/blog">Blog</a></li>`,
	`<li><a href="/contact">Contact</a></li>`,
	`</ul>`,
	`</nav>`,
	`</header>`,
	`<main class="container">`,
	`<section class="hero">`,
	`<h1 class="hero-title">Welcome to My Page</h1>`,
	`<p class="hero-subtitle">Building awesome things with Go.</p>`,
	`<a href="/get-started" class="btn btn-primary">Get Started</a>`,
	`</section>`,
	`<section class="features">`,
	`<div class="card">`,
	`<h2 class="card-title">Fast</h2>`,
	`<p class="card-body">Blazing fast performance out of the box.</p>`,
	`</div>`,
	`<div class="card">`,
	`<h2 class="card-title">Simple</h2>`,
	`<p class="card-body">Clean and readable code that scales.</p>`,
	`</div>`,
	`<div class="card">`,
	`<h2 class="card-title">Reliable</h2>`,
	`<p class="card-body">Built with stability and correctness in mind.</p>`,
	`</div>`,
	`</section>`,
	`</main>`,
	`<footer class="site-footer">`,
	`<p>&copy; 2025 MyBrand. All rights reserved.</p>`,
	`<a href="/privacy">Privacy Policy</a>`,
	`<a href="/terms">Terms of Service</a>`,
	`<a href="/terms-in-Chinese"></a>`,
	`</footer>`,
	`<script src="/static/js/app.js"></script>`,
	`</body>`,
	`</html>`,
}
