// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: cdc-payment.proto

package pkgtypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CDCPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber   string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDCPayment) Reset() {
	*x = CDCPayment{}
	mi := &file_cdc_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDCPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDCPayment) ProtoMessage() {}

func (x *CDCPayment) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDCPayment.ProtoReflect.Descriptor instead.
func (*CDCPayment) Descriptor() ([]byte, []int) {
	return file_cdc_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CDCPayment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CDCPayment) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *CDCPayment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CDCPayment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CDCPayment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CDCPayment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CDCPaymentEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *CDCPayment            `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After         *CDCPayment            `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Source        *DebeziumSource        `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Transaction   *DebeziumTransaction   `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Op            string                 `protobuf:"bytes,5,opt,name=op,proto3" json:"op,omitempty"`
	TsMs          int64                  `protobuf:"varint,6,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDCPaymentEnvelope) Reset() {
	*x = CDCPaymentEnvelope{}
	mi := &file_cdc_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDCPaymentEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDCPaymentEnvelope) ProtoMessage() {}

func (x *CDCPaymentEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDCPaymentEnvelope.ProtoReflect.Descriptor instead.
func (*CDCPaymentEnvelope) Descriptor() ([]byte, []int) {
	return file_cdc_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CDCPaymentEnvelope) GetBefore() *CDCPayment {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *CDCPaymentEnvelope) GetAfter() *CDCPayment {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *CDCPaymentEnvelope) GetSource() *DebeziumSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CDCPaymentEnvelope) GetTransaction() *DebeziumTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CDCPaymentEnvelope) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *CDCPaymentEnvelope) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

var File_cdc_payment_proto protoreflect.FileDescriptor

const file_cdc_payment_proto_rawDesc = "" +
	"\n" +
	"\x11cdc-payment.proto\x12\bdebezium\x1a\fcommon.proto\"\xad\x01\n" +
	"\n" +
	"CDCPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x86\x02\n" +
	"\x12CDCPaymentEnvelope\x12,\n" +
	"\x06before\x18\x01 \x01(\v2\x14.debezium.CDCPaymentR\x06before\x12*\n" +
	"\x05after\x18\x02 \x01(\v2\x14.debezium.CDCPaymentR\x05after\x120\n" +
	"\x06source\x18\x03 \x01(\v2\x18.debezium.DebeziumSourceR\x06source\x12?\n" +
	"\vtransaction\x18\x04 \x01(\v2\x1d.debezium.DebeziumTransactionR\vtransaction\x12\x0e\n" +
	"\x02op\x18\x05 \x01(\tR\x02op\x12\x13\n" +
	"\x05ts_ms\x18\x06 \x01(\x03R\x04tsMsB9Z7github.com/k-code-yt/go-api-practice/kafka-cdc/pkgtypesb\x06proto3"

var (
	file_cdc_payment_proto_rawDescOnce sync.Once
	file_cdc_payment_proto_rawDescData []byte
)

func file_cdc_payment_proto_rawDescGZIP() []byte {
	file_cdc_payment_proto_rawDescOnce.Do(func() {
		file_cdc_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdc_payment_proto_rawDesc), len(file_cdc_payment_proto_rawDesc)))
	})
	return file_cdc_payment_proto_rawDescData
}

var file_cdc_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cdc_payment_proto_goTypes = []any{
	(*CDCPayment)(nil),          // 0: debezium.CDCPayment
	(*CDCPaymentEnvelope)(nil),  // 1: debezium.CDCPaymentEnvelope
	(*DebeziumSource)(nil),      // 2: debezium.DebeziumSource
	(*DebeziumTransaction)(nil), // 3: debezium.DebeziumTransaction
}
var file_cdc_payment_proto_depIdxs = []int32{
	0, // 0: debezium.CDCPaymentEnvelope.before:type_name -> debezium.CDCPayment
	0, // 1: debezium.CDCPaymentEnvelope.after:type_name -> debezium.CDCPayment
	2, // 2: debezium.CDCPaymentEnvelope.source:type_name -> debezium.DebeziumSource
	3, // 3: debezium.CDCPaymentEnvelope.transaction:type_name -> debezium.DebeziumTransaction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cdc_payment_proto_init() }
func file_cdc_payment_proto_init() {
	if File_cdc_payment_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdc_payment_proto_rawDesc), len(file_cdc_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cdc_payment_proto_goTypes,
		DependencyIndexes: file_cdc_payment_proto_depIdxs,
		MessageInfos:      file_cdc_payment_proto_msgTypes,
	}.Build()
	File_cdc_payment_proto = out.File
	file_cdc_payment_proto_goTypes = nil
	file_cdc_payment_proto_depIdxs = nil
}
