// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: common.proto

package pkgtypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebeziumSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Connector     string                 `protobuf:"bytes,2,opt,name=connector,proto3" json:"connector,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TsMs          int64                  `protobuf:"varint,4,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Snapshot      string                 `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Db            string                 `protobuf:"bytes,6,opt,name=db,proto3" json:"db,omitempty"`
	Sequence      string                 `protobuf:"bytes,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TsUs          int64                  `protobuf:"varint,8,opt,name=ts_us,json=tsUs,proto3" json:"ts_us,omitempty"`
	TsNs          int64                  `protobuf:"varint,9,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	Schema        string                 `protobuf:"bytes,10,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,11,opt,name=table,proto3" json:"table,omitempty"`
	TxId          int64                  `protobuf:"varint,12,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Lsn           int64                  `protobuf:"varint,13,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Xmin          int64                  `protobuf:"varint,14,opt,name=xmin,proto3" json:"xmin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebeziumSource) Reset() {
	*x = DebeziumSource{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebeziumSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebeziumSource) ProtoMessage() {}

func (x *DebeziumSource) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebeziumSource.ProtoReflect.Descriptor instead.
func (*DebeziumSource) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *DebeziumSource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DebeziumSource) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *DebeziumSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DebeziumSource) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *DebeziumSource) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *DebeziumSource) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DebeziumSource) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *DebeziumSource) GetTsUs() int64 {
	if x != nil {
		return x.TsUs
	}
	return 0
}

func (x *DebeziumSource) GetTsNs() int64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *DebeziumSource) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *DebeziumSource) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DebeziumSource) GetTxId() int64 {
	if x != nil {
		return x.TxId
	}
	return 0
}

func (x *DebeziumSource) GetLsn() int64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *DebeziumSource) GetXmin() int64 {
	if x != nil {
		return x.Xmin
	}
	return 0
}

type DebeziumTransaction struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalOrder          int64                  `protobuf:"varint,2,opt,name=total_order,json=totalOrder,proto3" json:"total_order,omitempty"`
	DataCollectionOrder int64                  `protobuf:"varint,3,opt,name=data_collection_order,json=dataCollectionOrder,proto3" json:"data_collection_order,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DebeziumTransaction) Reset() {
	*x = DebeziumTransaction{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebeziumTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebeziumTransaction) ProtoMessage() {}

func (x *DebeziumTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebeziumTransaction.ProtoReflect.Descriptor instead.
func (*DebeziumTransaction) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *DebeziumTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DebeziumTransaction) GetTotalOrder() int64 {
	if x != nil {
		return x.TotalOrder
	}
	return 0
}

func (x *DebeziumTransaction) GetDataCollectionOrder() int64 {
	if x != nil {
		return x.DataCollectionOrder
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bdebezium\"\xcc\x02\n" +
	"\x0eDebeziumSource\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\tconnector\x18\x02 \x01(\tR\tconnector\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x13\n" +
	"\x05ts_ms\x18\x04 \x01(\x03R\x04tsMs\x12\x1a\n" +
	"\bsnapshot\x18\x05 \x01(\tR\bsnapshot\x12\x0e\n" +
	"\x02db\x18\x06 \x01(\tR\x02db\x12\x1a\n" +
	"\bsequence\x18\a \x01(\tR\bsequence\x12\x13\n" +
	"\x05ts_us\x18\b \x01(\x03R\x04tsUs\x12\x13\n" +
	"\x05ts_ns\x18\t \x01(\x03R\x04tsNs\x12\x16\n" +
	"\x06schema\x18\n" +
	" \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\v \x01(\tR\x05table\x12\x13\n" +
	"\x05tx_id\x18\f \x01(\x03R\x04txId\x12\x10\n" +
	"\x03lsn\x18\r \x01(\x03R\x03lsn\x12\x12\n" +
	"\x04xmin\x18\x0e \x01(\x03R\x04xmin\"z\n" +
	"\x13DebeziumTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtotal_order\x18\x02 \x01(\x03R\n" +
	"totalOrder\x122\n" +
	"\x15data_collection_order\x18\x03 \x01(\x03R\x13dataCollectionOrderB9Z7github.com/k-code-yt/go-api-practice/kafka-cdc/pkgtypesb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(*DebeziumSource)(nil),      // 0: debezium.DebeziumSource
	(*DebeziumTransaction)(nil), // 1: debezium.DebeziumTransaction
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
