// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: shared/ptypes.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistanceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Timestamp     int32                  `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceProto) Reset() {
	*x = DistanceProto{}
	mi := &file_shared_ptypes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceProto) ProtoMessage() {}

func (x *DistanceProto) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceProto.ProtoReflect.Descriptor instead.
func (*DistanceProto) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{0}
}

func (x *DistanceProto) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DistanceProto) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DistanceProto) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SaveInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      *DistanceProto         `protobuf:"bytes,1,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInvoiceRequest) Reset() {
	*x = SaveInvoiceRequest{}
	mi := &file_shared_ptypes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInvoiceRequest) ProtoMessage() {}

func (x *SaveInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInvoiceRequest.ProtoReflect.Descriptor instead.
func (*SaveInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{1}
}

func (x *SaveInvoiceRequest) GetDistance() *DistanceProto {
	if x != nil {
		return x.Distance
	}
	return nil
}

type SaveInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInvoiceResponse) Reset() {
	*x = SaveInvoiceResponse{}
	mi := &file_shared_ptypes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInvoiceResponse) ProtoMessage() {}

func (x *SaveInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInvoiceResponse.ProtoReflect.Descriptor instead.
func (*SaveInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{2}
}

func (x *SaveInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveInvoiceResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_shared_ptypes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{3}
}

func (x *GetInvoiceRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type InvoiceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceProto) Reset() {
	*x = InvoiceProto{}
	mi := &file_shared_ptypes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceProto) ProtoMessage() {}

func (x *InvoiceProto) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceProto.ProtoReflect.Descriptor instead.
func (*InvoiceProto) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{4}
}

func (x *InvoiceProto) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *InvoiceProto) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InvoiceProto) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *InvoiceProto          `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_shared_ptypes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvoiceResponse) GetInvoice() *InvoiceProto {
	if x != nil {
		return x.Invoice
	}
	return nil
}

var File_shared_ptypes_proto protoreflect.FileDescriptor

const file_shared_ptypes_proto_rawDesc = "" +
	"\n" +
	"\x13shared/ptypes.proto\"S\n" +
	"\rDistanceProto\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x01R\x05Value\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x05R\tTimestamp\"@\n" +
	"\x12SaveInvoiceRequest\x12*\n" +
	"\bdistance\x18\x01 \x01(\v2\x0e.DistanceProtoR\bdistance\"A\n" +
	"\x13SaveInvoiceResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"R\n" +
	"\fInvoiceProto\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x01R\x06Amount\x12\x1a\n" +
	"\bCategory\x18\x03 \x01(\tR\bCategory\"=\n" +
	"\x12GetInvoiceResponse\x12'\n" +
	"\ainvoice\x18\x01 \x01(\v2\r.InvoiceProtoR\ainvoice2S\n" +
	"\x17InvoiceTransportService\x128\n" +
	"\vSaveInvoice\x12\x13.SaveInvoiceRequest\x1a\x14.SaveInvoiceResponse2V\n" +
	"\x1dGetterInvoiceTransportService\x125\n" +
	"\n" +
	"GetInvoice\x12\x12.GetInvoiceRequest\x1a\x13.GetInvoiceResponseB-Z+github.com/k-code-yt/go-api-practice/sharedb\x06proto3"

var (
	file_shared_ptypes_proto_rawDescOnce sync.Once
	file_shared_ptypes_proto_rawDescData []byte
)

func file_shared_ptypes_proto_rawDescGZIP() []byte {
	file_shared_ptypes_proto_rawDescOnce.Do(func() {
		file_shared_ptypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_ptypes_proto_rawDesc), len(file_shared_ptypes_proto_rawDesc)))
	})
	return file_shared_ptypes_proto_rawDescData
}

var file_shared_ptypes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_ptypes_proto_goTypes = []any{
	(*DistanceProto)(nil),       // 0: DistanceProto
	(*SaveInvoiceRequest)(nil),  // 1: SaveInvoiceRequest
	(*SaveInvoiceResponse)(nil), // 2: SaveInvoiceResponse
	(*GetInvoiceRequest)(nil),   // 3: GetInvoiceRequest
	(*InvoiceProto)(nil),        // 4: InvoiceProto
	(*GetInvoiceResponse)(nil),  // 5: GetInvoiceResponse
}
var file_shared_ptypes_proto_depIdxs = []int32{
	0, // 0: SaveInvoiceRequest.distance:type_name -> DistanceProto
	4, // 1: GetInvoiceResponse.invoice:type_name -> InvoiceProto
	1, // 2: InvoiceTransportService.SaveInvoice:input_type -> SaveInvoiceRequest
	3, // 3: GetterInvoiceTransportService.GetInvoice:input_type -> GetInvoiceRequest
	2, // 4: InvoiceTransportService.SaveInvoice:output_type -> SaveInvoiceResponse
	5, // 5: GetterInvoiceTransportService.GetInvoice:output_type -> GetInvoiceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_ptypes_proto_init() }
func file_shared_ptypes_proto_init() {
	if File_shared_ptypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_ptypes_proto_rawDesc), len(file_shared_ptypes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shared_ptypes_proto_goTypes,
		DependencyIndexes: file_shared_ptypes_proto_depIdxs,
		MessageInfos:      file_shared_ptypes_proto_msgTypes,
	}.Build()
	File_shared_ptypes_proto = out.File
	file_shared_ptypes_proto_goTypes = nil
	file_shared_ptypes_proto_depIdxs = nil
}
