// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: shared/ptypes.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistanceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Timestamp     int32                  `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceProto) Reset() {
	*x = DistanceProto{}
	mi := &file_shared_ptypes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceProto) ProtoMessage() {}

func (x *DistanceProto) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceProto.ProtoReflect.Descriptor instead.
func (*DistanceProto) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{0}
}

func (x *DistanceProto) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DistanceProto) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DistanceProto) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SaveInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      *DistanceProto         `protobuf:"bytes,1,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInvoiceRequest) Reset() {
	*x = SaveInvoiceRequest{}
	mi := &file_shared_ptypes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInvoiceRequest) ProtoMessage() {}

func (x *SaveInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInvoiceRequest.ProtoReflect.Descriptor instead.
func (*SaveInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{1}
}

func (x *SaveInvoiceRequest) GetDistance() *DistanceProto {
	if x != nil {
		return x.Distance
	}
	return nil
}

type SaveInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInvoiceResponse) Reset() {
	*x = SaveInvoiceResponse{}
	mi := &file_shared_ptypes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInvoiceResponse) ProtoMessage() {}

func (x *SaveInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInvoiceResponse.ProtoReflect.Descriptor instead.
func (*SaveInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{2}
}

func (x *SaveInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveInvoiceResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_shared_ptypes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{3}
}

func (x *GetInvoiceRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type InvoiceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceProto) Reset() {
	*x = InvoiceProto{}
	mi := &file_shared_ptypes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceProto) ProtoMessage() {}

func (x *InvoiceProto) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceProto.ProtoReflect.Descriptor instead.
func (*InvoiceProto) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{4}
}

func (x *InvoiceProto) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *InvoiceProto) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InvoiceProto) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *InvoiceProto          `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_shared_ptypes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvoiceResponse) GetInvoice() *InvoiceProto {
	if x != nil {
		return x.Invoice
	}
	return nil
}

// ---STREAMING---
type SensorDataProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDataProto) Reset() {
	*x = SensorDataProto{}
	mi := &file_shared_ptypes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDataProto) ProtoMessage() {}

func (x *SensorDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDataProto.ProtoReflect.Descriptor instead.
func (*SensorDataProto) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{6}
}

func (x *SensorDataProto) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SensorDataProto) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SensorDataProto) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type SensorDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SensorDataProto       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDataRequest) Reset() {
	*x = SensorDataRequest{}
	mi := &file_shared_ptypes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDataRequest) ProtoMessage() {}

func (x *SensorDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDataRequest.ProtoReflect.Descriptor instead.
func (*SensorDataRequest) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{7}
}

func (x *SensorDataRequest) GetData() *SensorDataProto {
	if x != nil {
		return x.Data
	}
	return nil
}

type SensorDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SensorDataProto       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDataResponse) Reset() {
	*x = SensorDataResponse{}
	mi := &file_shared_ptypes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDataResponse) ProtoMessage() {}

func (x *SensorDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDataResponse.ProtoReflect.Descriptor instead.
func (*SensorDataResponse) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{8}
}

func (x *SensorDataResponse) GetData() *SensorDataProto {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_shared_ptypes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SavePath      string                 `protobuf:"bytes,3,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	BytesReceived int64                  `protobuf:"varint,4,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_shared_ptypes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ptypes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_shared_ptypes_proto_rawDescGZIP(), []int{10}
}

func (x *FileUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileUploadResponse) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *FileUploadResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_shared_ptypes_proto protoreflect.FileDescriptor

const file_shared_ptypes_proto_rawDesc = "" +
	"\n" +
	"\x13shared/ptypes.proto\"S\n" +
	"\rDistanceProto\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x01R\x05Value\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x05R\tTimestamp\"@\n" +
	"\x12SaveInvoiceRequest\x12*\n" +
	"\bdistance\x18\x01 \x01(\v2\x0e.DistanceProtoR\bdistance\"A\n" +
	"\x13SaveInvoiceResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"R\n" +
	"\fInvoiceProto\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x01R\x06Amount\x12\x1a\n" +
	"\bCategory\x18\x03 \x01(\tR\bCategory\"=\n" +
	"\x12GetInvoiceResponse\x12'\n" +
	"\ainvoice\x18\x01 \x01(\v2\r.InvoiceProtoR\ainvoice\"E\n" +
	"\x0fSensorDataProto\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\"9\n" +
	"\x11SensorDataRequest\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.SensorDataProtoR\x04data\":\n" +
	"\x12SensorDataResponse\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.SensorDataProtoR\x04data\"\x81\x01\n" +
	"\tFileChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x03R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"\x8c\x01\n" +
	"\x12FileUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tsave_path\x18\x03 \x01(\tR\bsavePath\x12%\n" +
	"\x0ebytes_received\x18\x04 \x01(\x03R\rbytesReceived2S\n" +
	"\x17InvoiceTransportService\x128\n" +
	"\vSaveInvoice\x12\x13.SaveInvoiceRequest\x1a\x14.SaveInvoiceResponse2V\n" +
	"\x1dGetterInvoiceTransportService\x125\n" +
	"\n" +
	"GetInvoice\x12\x12.GetInvoiceRequest\x1a\x13.GetInvoiceResponse2\x8d\x01\n" +
	"\x19StreamingTransportSerivce\x12?\n" +
	"\x10SensorDataStream\x12\x12.SensorDataRequest\x1a\x13.SensorDataResponse(\x010\x01\x12/\n" +
	"\n" +
	"UploadFile\x12\n" +
	".FileChunk\x1a\x13.FileUploadResponse(\x01B-Z+github.com/k-code-yt/go-api-practice/sharedb\x06proto3"

var (
	file_shared_ptypes_proto_rawDescOnce sync.Once
	file_shared_ptypes_proto_rawDescData []byte
)

func file_shared_ptypes_proto_rawDescGZIP() []byte {
	file_shared_ptypes_proto_rawDescOnce.Do(func() {
		file_shared_ptypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_ptypes_proto_rawDesc), len(file_shared_ptypes_proto_rawDesc)))
	})
	return file_shared_ptypes_proto_rawDescData
}

var file_shared_ptypes_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shared_ptypes_proto_goTypes = []any{
	(*DistanceProto)(nil),       // 0: DistanceProto
	(*SaveInvoiceRequest)(nil),  // 1: SaveInvoiceRequest
	(*SaveInvoiceResponse)(nil), // 2: SaveInvoiceResponse
	(*GetInvoiceRequest)(nil),   // 3: GetInvoiceRequest
	(*InvoiceProto)(nil),        // 4: InvoiceProto
	(*GetInvoiceResponse)(nil),  // 5: GetInvoiceResponse
	(*SensorDataProto)(nil),     // 6: SensorDataProto
	(*SensorDataRequest)(nil),   // 7: SensorDataRequest
	(*SensorDataResponse)(nil),  // 8: SensorDataResponse
	(*FileChunk)(nil),           // 9: FileChunk
	(*FileUploadResponse)(nil),  // 10: FileUploadResponse
}
var file_shared_ptypes_proto_depIdxs = []int32{
	0,  // 0: SaveInvoiceRequest.distance:type_name -> DistanceProto
	4,  // 1: GetInvoiceResponse.invoice:type_name -> InvoiceProto
	6,  // 2: SensorDataRequest.data:type_name -> SensorDataProto
	6,  // 3: SensorDataResponse.data:type_name -> SensorDataProto
	1,  // 4: InvoiceTransportService.SaveInvoice:input_type -> SaveInvoiceRequest
	3,  // 5: GetterInvoiceTransportService.GetInvoice:input_type -> GetInvoiceRequest
	7,  // 6: StreamingTransportSerivce.SensorDataStream:input_type -> SensorDataRequest
	9,  // 7: StreamingTransportSerivce.UploadFile:input_type -> FileChunk
	2,  // 8: InvoiceTransportService.SaveInvoice:output_type -> SaveInvoiceResponse
	5,  // 9: GetterInvoiceTransportService.GetInvoice:output_type -> GetInvoiceResponse
	8,  // 10: StreamingTransportSerivce.SensorDataStream:output_type -> SensorDataResponse
	10, // 11: StreamingTransportSerivce.UploadFile:output_type -> FileUploadResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_shared_ptypes_proto_init() }
func file_shared_ptypes_proto_init() {
	if File_shared_ptypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_ptypes_proto_rawDesc), len(file_shared_ptypes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_shared_ptypes_proto_goTypes,
		DependencyIndexes: file_shared_ptypes_proto_depIdxs,
		MessageInfos:      file_shared_ptypes_proto_msgTypes,
	}.Build()
	File_shared_ptypes_proto = out.File
	file_shared_ptypes_proto_goTypes = nil
	file_shared_ptypes_proto_depIdxs = nil
}
